### ISSUE TITLE
Windows: fatal error C1083: Cannot open include file: 'qdldl_types.h'

### ISSUE THREAD

**Issue by stephane-caron** [osqp/qdldl#42]
@WCHIHO is reporting the following build error on Windows (Microsoft Visual Studio Community 2018 using Python environment including MSBuild) when installing via ``pip install qpsolvers``, which depends on qdldl. The build seems to fail at qdldl:

```
" running build_ext
-- Selecting Windows SDK version to target Windows 10.0.19043.
CMake Error at CMakeLists.txt:4 (project):
Failed to run MSBuild command:

  MSBuild.exe

to get the value of VCTargetsPath:

  The system cannot find the file specified. 

cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
qdldl.cpp
c\qdldl/include/qdldl.h(5): fatal error C1083: Cannot open include file: 'qdldl_types.h': No such file or directory
error: command 'C:\Program Files\Microsoft Visual "
```

More details at https://github.com/stephane-caron/qpsolvers/commit/8016a01f275167097617ceadeb702151ab2707c9#commitcomment-60090952

This looks similar to [this SO question](https://stackoverflow.com/questions/58940455/trouble-installing-osqp-package) but it should have been fixed with the pip wheels. :thinking:

Any insight as to what is causing this build failure?

**Comment by stephane-caron** [comment]
@WCHIHO I have just tried installing from PyPI from Microsoft Visual Studio Community 2022 (Tools → Python → Python Environments) and the installation was successful for both the Python 3.8 and Python 3.9 environments.

It seems you are using an older version of MVSC. Is your Python version >= 3.8?

It seems the qdldl wheels are not available for older versions of Python, which would explain this build error.

**Comment by WCHIHO** [comment]
Hello,

 

Thank you for your helpful replies.

 

You are right. My existing python package is 3.8.8 whilst I use Jupyter notebook  and VS Code to run the programmes. I immediately updated my python package to 3.10. I then used VS Code to run “pip install qpsolvers”. The installation process was much complex and lengthy. It kept going down the scipy version from say 1.56 to 1.40. Eventually the installation was successful. The results can be described below:

 

PS D:\> pip install qpsolvers

Requirement already satisfied: qpsolvers in c:\users\wchih\appdata\local\programs\python\python310-32\lib\site-packages (1.7.0)

Requirement already satisfied: quadprog>=0.1.8 in c:\users\wchih\appdata\local\programs\python\python310-32\lib\site-packages (from qpsolvers) (0.1.10)

Requirement already satisfied: numpy in c:\users\wchih\appdata\local\programs\python\python310-32\lib\site-packages (from quadprog>=0.1.8->qpsolvers) (1.21.4)

 

I also checked the results in Jupyter Notebook using “!pip list”:

 

Package    Version

---------- -------

numpy      1.21.4

pip        21.3.1

pybind11   2.8.1

qpsolvers  1.7.0

quadprog   0.1.10

setuptools 58.5.3

wheel      0.37.0

 

Well, I noted my Juypter Notebook is still using python 3.8.8:

 

You are using Jupyter notebook.

The version of the notebook server is: 6.3.0
The server is running on this version of Python:



Python 3.8.8 (default, Apr 13 2021, 15:08:07) [MSC v.1916 32 bit (Intel)]

 

When I ran in Jupyter Notebook “from qpsolvers import solve_qp”, I got this error:

 

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-20-b46fa005102a> in <module>
----> 1 from qpsolvers import solve_qp
 
ModuleNotFoundError: No module named 'qpsolvers'
 
 
So, I used Visual Studio Code to run your programme:
 

rom numpy import array, dot

from qpsolvers import solve_qp

 

M = array([[1., 2., 0.], [-8., 3., 2.], [0., 1., 1.]])

P = dot(M.T, M)  # this is a positive definite matrix

q = dot(array([3., 2., 3.]), M).reshape((3,))

G = array([[1., 2., 1.], [2., 0., 1.], [-1., 2., -1.]])

h = array([3., 2., -2.]).reshape((3,))

A = array([1., 1., 1.])

b = array([1.])

 

x = solve_qp(P, q, G, h, A, b)

print("QP solution: x = {}".format(x))

 

 

But, I got the same error as in Jupyter Notebook:

 

“from qpsolvers import solve_qp

ModuleNotFoundError: No module named 'qpsolvers'”

 

This is strange because 'qpsolvers' has been successfully installed.

 

Can you enlighten me as to what is going on here? 

 

Should I use another terminal to run your programme given that 'qpsolvers' is installed? By the way which terminal you use to run your 'qpsolvers' programme?

I have thought about using Visual Studio Community 2019. But, I have not tried it.

 

Many thanks. It is appreciated.

 

Kindest regards,

William

**Comment by stephane-caron** [comment]
OK, then the issue is not related to qdldl any more. Let's close this and continue with your issue at https://github.com/stephane-caron/qpsolvers/issues/48
